In [1]:
# Run these following 3 installs to if you don't have shapely, geopands, etc
# if you are using sagemaker, you should use the "conda_python3" kernel
#!pip install laspy
#!pip install geopandas
#!pip install shapely

In [2]:
# Run these following 2 installs to install/upgrade database interface modules
#!pip install sqlalchemy psycopg2
#!pip install psycopg2-binary
!pip install geoalchemy2

Requirement already satisfied: geoalchemy2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (0.7.0)
Requirement already satisfied: SQLAlchemy>=0.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from geoalchemy2) (1.2.11)
You are using pip version 10.0.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [3]:
### install/upgrade folium mapping tools
# !pip install folium

In [4]:
import boto3
import json

In [5]:
import numpy as np
import pandas as pd
import psycopg2
import sqlalchemy as db
import matplotlib as plt

%matplotlib inline

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [6]:
from sqlalchemy import update 
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

In [7]:
#Get information from Secrets Manager, especially about the database
secretsmanager_client = boto3.client('secretsmanager')
dbSecretValues = secretsmanager_client.get_secret_value(SecretId='Postgres-GISDB')

In [8]:
dbSecretValuesJson = json.loads(dbSecretValues['SecretString'])
#uncomment the following line to confirm the Database access information
#dbSecretValuesJson

In [9]:
from sqlalchemy import create_engine
# Postgres username, password, and database name
POSTGRES_ADDRESS = dbSecretValuesJson['POSTGRES_ADDRESS'] ## INSERT YOUR DB ADDRESS IF IT'S NOT ON PANOPLY
POSTGRES_PORT = int(dbSecretValuesJson['POSTGRES_PORT'])
POSTGRES_USERNAME = dbSecretValuesJson['POSTGRES_USERNAME'] ## CHANGE THIS TO YOUR PANOPLY/POSTGRES USERNAME
POSTGRES_PASSWORD = dbSecretValuesJson['POSTGRES_PASSWORD'] ## CHANGE THIS TO YOUR PANOPLY/POSTGRES PASSWORD POSTGRES_DBNAME = 'database' ## CHANGE THIS TO YOUR DATABASE NAME
POSTGRES_DBNAME = dbSecretValuesJson['POSTGRES_DBNAME']
# A long string that contains the necessary Postgres login information
# postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(
#     username=POSTGRES_USERNAME,
#     password=POSTGRES_PASSWORD,
#     ipaddress=POSTGRES_ADDRESS,
#     port=POSTGRES_PORT,
#     dbname=POSTGRES_DBNAME))
postgres_str = f"postgresql://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_ADDRESS}/{POSTGRES_DBNAME}"

engine = create_engine(postgres_str)
connection = engine.connect()
metadata = db.MetaData()
building_detailed_info_table = db.Table('building_detailed_info_within_ajjits_selected_tracts', metadata, autoload=True, autoload_with=engine)

In [21]:
#Get the las grid that belong to a building, get the percentil numbers and enter them into the table
#engie is the postgres sqlalchemy engine
def query_and_update_sql_table_with_height_pct(bldgid, engine, connection, building_detailed_info_table): 
#     sql_string = "select * from building_detailed_info_within_ajjits_selected_tracts where bldgid = 59026".format(bldgid)
#     pd.read_sql_query(sql_string, engine)
    sql_string = """select las_grnd_coord, lidar_z, intensity, classification, scan_angle, synthetic, withheld from lidarbuildingmatchtest 
        where bldgid = {0} and classification <> ALL (ARRAY[3, 4, 5])""".format(bldgid) 
    #the sql string removes all vegetation related points
    las_within_bldg_border_df = pd.read_sql_query(sql_string, engine)
    if(las_within_bldg_border_df.size > 0):
        las_qt_results_df = las_within_bldg_border_df[['lidar_z']].quantile([.999, .995, .99, .95, .90])
        pct999 = las_qt_results_df.loc[.999, 'lidar_z']
        pct995 = las_qt_results_df.loc[.995, 'lidar_z']
        pct990 = las_qt_results_df.loc[.990, 'lidar_z']
        pct950 = las_qt_results_df.loc[.950, 'lidar_z']
        pct900 = las_qt_results_df.loc[.900, 'lidar_z']

        query = db.update(building_detailed_info_table).values({'pct999': pct999, 'pct995': pct995, 'pct990': pct990, 'pct950': pct950})
        query = query.where(building_detailed_info_table.columns.bldgid == bldgid)
        ResultProxy = connection.execute(query)
        ResultProxy

In [22]:
sql_string = """select las_grnd_coord, lidar_z, intensity, classification, scan_angle, synthetic, withheld from lidarbuildingmatchtest 
        where bldgid = {0}""".format(70414)
las_within_bldg_border_df = pd.read_sql_query(sql_string, engine)
las_within_bldg_border_df

,las_grnd_coord,lidar_z,intensity,classification,scan_angle,synthetic,withheld
0,01010000807B721230FF4253C0DEA449031673434085EB...,23.02,9916.0,4,-3.0,0,0
1,01010000808838C929FF4253C0747B8902167343407B14...,21.48,18614.0,4,-3.0,0,0

In [23]:
query_and_update_sql_table_with_height_pct(59945, engine, connection, building_detailed_info_table)

In [24]:
sql_string = """select bldgid from building_detailed_info_within_ajjits_selected_tracts"""
bldgid_within_ajjit_tracts = pd.read_sql_query(sql_string, engine)
bldgid_within_ajjit_tracts.head()

   bldgid
0   59026
1   59450
2   59547
3   59576
4   59727

In [25]:
for index, row in bldgid_within_ajjit_tracts.iterrows():
    print (index, row['bldgid'])
    bldgid = np.int(row['bldgid'])
    query_and_update_sql_table_with_height_pct(bldgid, engine, connection, building_detailed_info_table)

0 59026
1 59450
2 59547
3 59576
4 59727
5 59730
6 59769
7 59889
8 59930
9 59909
10 60188
11 60220
12 60285
13 60289
14 60416
15 60421
16 60512
17 60517
18 60526
19 60527
20 60528
21 60558
22 60634
23 60641
24 60660
25 60769
26 60771
27 60806
28 60855
29 61016
30 61069
31 61095
32 61556
33 61584
34 61715
35 61747
36 61982
37 62036
38 62042
39 62135
40 62173
41 62174
42 62232
43 62283
44 62324
45 62378
46 62457
47 62538
48 62542
49 62630
50 62752
51 62736
52 62737
53 62749
54 62754
55 62824
56 62827
57 62845
58 62855
59 62857
60 62963
61 63035
62 63006
63 63011
64 63012
65 63015
66 63043
67 63072
68 63111
69 63128
70 63149
71 63169
72 63176
73 63193
74 63216
75 63273
76 63277
77 63358
78 63371
79 63428
80 63457
81 63467
82 63468
83 63478
84 63494
85 63553
86 63528
87 63563
88 63573
89 63578
90 63579
91 63591
92 63606
93 63630
94 63632
95 63640
96 63755
97 63812
98 63824
99 63849
100 63852
101 63853
102 63865
103 63875
104 63894
105 63898
106 63899
107 63900
108 63909
109 63935
110 63957
111 63958
112 63976
113 63978
114 64038
115 63992
116 64009
117 64033
118 64048
119 64052
120 64059
121 64060
122 64062
123 64079
124 64081
125 64093
126 64118
127 64120
128 64140
129 64157
130 64168
131 64176
132 64185
133 64186
134 64187
135 64209
136 64225
137 64317
138 64359
139 64394
140 64442
141 64400
142 64402
143 64403
144 64405
145 64407
146 64409
147 64413
148 64414
149 64415
150 64418
151 64420
152 64421
153 64424
154 64426
155 64436
156 64437
157 64430
158 64431
159 64434
160 64435
161 64444
162 64468
163 64503
164 64514
165 64539
166 64548
167 64559
168 64590
169 64596
170 64606
171 64607
172 64616
173 64648
174 64719
175 64721
176 64774
177 64777
178 64813
179 64805
180 64809
181 64810
182 64814
183 64823
184 64869
185 64872
186 64915
187 64927
188 64929
189 65022
190 65039
191 65058
192 65091
193 65099
194 65134
195 65151
196 65220
197 65225
198 65240
199 65242
200 65244
201 65246
202 65319
203 65327
204 65346
205 65373
206 65396
207 65404
208 65412
209 65435
210 65437
211 65479
212 65481
213 65599
214 65652
215 65653
216 65655
217 65657
218 65718
219 65719
220 65661
221 65684
222 65688
223 65692
224 65700
225 65725
226 65731
227 66000
228 66001
229 66018
230 66002
231 66016
232 66025
233 66030
234 66073
235 66077
236 66078
237 66079
238 66080
239 66081
240 66083
241 66087
242 66116
243 66430
244 66167
245 66194
246 66201
247 66211
248 66230
249 66232
250 66243
251 66260
252 66292
253 66293
254 66317
255 66318
256 66353
257 66354
258 66364
259 66367
260 66377
261 66392
262 66406
263 66427
264 66419
265 66428
266 66443
267 66445
268 66448
269 66478
270 66480
271 66506
272 66510
273 66518
274 66526
275 66535
276 66568
277 66720
278 66724
279 66870
280 66884
281 66920
282 66935
283 66936
284 66956
285 66962
286 67016
287 67020
288 67027
289 67030
290 67031
291 67033
292 67034
293 67036
294 67048
295 67072
296 67174
297 67221
298 67253
299 67273
300 67274
301 67275
302 67277
303 67278
304 67279
305 67281
306 67282
307 67283
308 67284
309 67287
310 67289
311 67293
312 67303
313 67306
314 67327
315 67308
316 67313
317 67319
318 67337
319 67349
320 67350
321 67423
322 67434
323 67437
324 67452
325 67448
326 67529
327 67593
328 67599
329 67650
330 67680
331 67682
332 67747
333 67751
334 67755
335 67756
336 67796
337 67892
338 67899
339 67974
340 67976
341 67987
342 68008
343 68018
344 68020
345 68021
346 68022
347 68023
348 68036
349 68083
350 68092
351 68101
352 68123
353 68143
354 68176
355 68232
356 68243
357 68274
358 68315
359 68328
360 68329
361 68348
362 68349
363 68367
364 68400
365 68420
366 68442
367 68472
368 68529
369 68532
370 68533
371 68535
372 68536
373 68566
374 68578
375 68593
376 68621
377 68631
378 68667
379 68674
380 68708
381 68725
382 68727
383 68729
384 68742
385 68745
386 68769
387 68761
388 68774
389 68780
390 68799
391 68804
392 68806
393 68822
394 68825
395 68835
396 68854
397 68864
398 68916
399 68973
400 68984
401 68987
402 69040
403 69058
404 69084
405 69086
406 69137
407 69090
408 69091
409 69098
410 69100
411 69103
412 69104
413 69105
414 69106
415 69107
416 69112
417 69116
418 69256
419 69263
420 69282
421 69305
422 69704
423 69359
424 69363
425 69391
426 69392
427 69402
428 69408
429 69425
430 69436
431 69447
432 69442
433 69461
434 69504
435 69540
436 69541
437 69543
438 69551
439 69560
440 69583
441 69592
442 69593
443 69597
444 69617
445 69625
446 69637
447 69709
448 69675
449 69711
450 69724
451 69736
452 69822
453 69811
454 69813
455 69823
456 69824
457 69827
458 69830
459 69832
460 69834
461 69838
462 69839
463 69841
464 69842
465 69843
466 69845
467 69846
468 69903
469 69939
470 69940
471 70052
472 70061
473 70127
474 70242
475 70181
476 70182
477 70197
478 70200
479 70203
480 70207
481 70229
482 70245
483 70246
484 70249
485 70260
486 70278
487 70301
488 70310
489 70398
490 70414
491 70489
492 70528
493 70551
494 70577
495 70599
496 70617
497 70795
498 70840
499 70841
500 70862
501 70871
502 70887
503 70930
504 70935
505 70937
506 70938
507 70948
508 70950
509 70953
510 70955
511 70956
512 70959
513 70960
514 70961
515 70963
516 70964
517 70965
518 70971
519 70972
520 70974
521 70975
522 70986
523 70988
524 70991
525 70994
526 71010
527 71031
528 71050
529 71054
530 71056
531 71063
532 71069
533 71073
534 71085
535 71087
536 71088
537 71124
538 71141
539 71174
540 71219
541 71264
542 71277
543 71286
544 71292
545 71310
546 71327
547 71335
548 71336
549 71359
550 71361
551 71370
552 71372
553 71416
554 71380
555 71401
556 71406
557 71409
558 71430
559 71439
560 71450
561 71463
562 71513
563 71531
564 71491
565 71493
566 71494
567 71495
568 71496
569 71497
570 71498
571 71503
572 71505
573 71510
574 71511
575 71516
576 71525
577 71558
578 71585
579 71600
580 71604
581 71640
582 71648
583 71658
584 71678
585 71684
586 71708
587 71711
588 71743
589 71829
590 71830
591 71842
592 71845
593 71860
594 71861
595 71888
596 71897
597 71917
598 71952
599 71959
600 71976
601 72073
602 72077
603 72100
604 72376
605 72785
606 72806
607 72808
608 72842
609 72875
610 73057
611 73577
612 74509
613 74862
614 74936
615 59945

In [26]:
connection.close()
#terminate connections and drop the db engine
engine.dispose()